### ISSUE TITLE
Water & Lava Eggs

### ISSUE THREAD

**Issue by penturt** [CreeperHost/Chickens#48]
Using:
chickensmod-1.19.2-1.0.30
forge-1.19.2 - 43.2.6

All other chickens seem to be dropping eggs, but the lava and water chicken don't seem to. After their laying timer finishes it just restarts and no eggs are produced.

https://ibb.co/Qrt3RX9

**Comment by xaelith** [comment]
Just dug into the config recently, and noticed that the one for FTB One and StoneBlock3 are different, yet I know the eggs work in SB3. Maybe this will help?

**Edit 24MAR2023 18:32** - Okay, dug a little deeper on this last night and did some testing via modifying the config json and then launcing (or attempting to launch) FTB One via FTB App. One thing I did notice before all this but didn't pay attention to is that the liquid egg doesn't show up in FTB One when "@chickens" is searched in JEI, but it does appear in StoneBlock 3.

In the code for the mod itself, the references to the liquid egg are different between the two versions (and I apologize for not realizing that StoneBlock3 is 1.18, and not 1.19). In the StoneBlock version, there appears to be more lines of code in the handler for the liquid egg, which may or may not explain why it works. It could also be that more code is necessary for 1.18 than 1.19, I'm not sure (still a little newish at reading code, especially Java).

Anyway, I tried to do what I hinted at in my previous comment. I changed FTB One's config info for the water chicken to match exactly what was written in StoneBlock 3's, and the modpack would crash at the point that the main screen should be displayed. I tried changing different info, tried using "liquid_egg", "liquidegg" and "fluid_egg", all without success. Oddly enough, the game will still launch if the "nbt" and "id" lines are added after the "water_fluid_egg" line, but no discernable difference is made to gameplay. Another odd feature is that if the fluid egg is instead changed to "minecraft:water_bucket", then the chickens just literally do nothing (probably due to water buckets not stacking normally).

I'm not sure what else to try, but I will continue to attempt helping with this and any other issues that arise. :) Hope this helps
