### ISSUE TITLE
How to add new chickens to the mod?

### ISSUE THREAD

**Issue by BV-Doan** [CreeperHost/Chickens#58]
I want to add some ingredients from another mod but I can't find a way to do it online.

**Comment by xaelith** [comment]
> I want to add some ingredients from another mod but I can't find a way to do it online.

The "chickens.json" in the "config->chickens" folder of your instance has an example commented out in the top of the file. I also used to copy and paste the code for one of the already-implemented chickens when I was starting out, and changed only the values I was interested in (especially because format matters). Stoneblock 3 and FTB One are also good examples. It's helpful to have advanced tooltips turned on in-game (F3+H) to give the tag associated with the preferred ingredient, as the tag will be necessary in the config to have the custom chicken lay/drop the proper item. Lastly, knowing how to create a datapack or using/having kubejs in the modpack helps a ton.

I apologize if this isn't as helpful as you were hoping, but here isn't the proper location for a complete walkthrough :)

**Comment by BV-Doan** [comment]
It worked. Thank.
