### ISSUE TITLE
Two Different Mod Pages??

### ISSUE THREAD

**Issue by Waterspark63** [CreeperHost/Chickens#72]
Uh, I just found out that there are two different project pages on Curseforge, linking to this repo, are they both meant to be linked here?

[CreeperHost Presents Chickens](https://www.curseforge.com/minecraft/mc-mods/creeperhost-presents-chickens)
[Chickens 2](https://www.curseforge.com/minecraft/mc-mods/chickens-2)

Is there a reason why there's a duplicate (and different) mod page?

**Comment by xaelith** [comment]
Looking at the two pages, it seems the "CreeperHost Presents" mod is a port of an old mod, and therefore works very similarly. Conversely, Chickens 2 is a complete reimagining of the mod. Instead of the tried-and-true "breed chickens, stuff in box, get resources", there's a few new mechanics at play. On the Chickens2 page, it mentions the resources coming from the eggs instead of the chickens themselves, and a lifespan for the mobs in some fashion.

**Comment by Waterspark63** [comment]
I understand that they appear to advertise two different mods, I was wondering if they were meant to both be pointed *here*, or if Chickens 2 has it's own repo, and was mistakenly pointed here, or the inverse for Creeperhost mistakenly being pointed to Chickens 2's repo, or if one of the two has been discontinued, hence both being pointed here.

**Comment by ThePaul-T** [comment]
We will still do bug fixes for Chickens 1, but no further ports as someone else appears to have ported to newer versions. So all newer MC versions will be Chickens 2, which is "original content" inspired by the concept of Chickens 1.
